import { INodeProperties } from 'n8n-workflow';

export const documentActionsOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['documentActions'] } },
		options: [
			{ name: 'Send to Signers', value: 'send', description: 'Send a document to its signers', action: 'Send a document to signers' },
			{ name: 'Cancel Document', value: 'cancel', description: 'Cancel a document', action: 'Cancel a document' },
			{ name: 'Download Document', value: 'download', description: 'Request a download link and fetch the file', action: 'Download a document' },
			{ name: 'Add Highlight', value: 'addHighlight', description: 'Add a highlighted clause to a document', action: 'Add highlight' },
			{ name: 'Resend Signature Link', value: 'resend', description: 'Resend the signing link to a signer', action: 'Resend signature link' },
		],
		default: 'send',
	},
];

export const documentActionsFields: INodeProperties[] = [
	{
		displayName: 'Document UUID',
		name: 'documentUuid',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['documentActions'], operation: ['send', 'cancel', 'download', 'addHighlight', 'resend'] } },
		description: 'UUID of the document',
	},
	{
		displayName: 'Message',
		name: 'message',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['documentActions'], operation: ['send'] } },
		description: 'Message to send to signers',
	},
	{
		displayName: 'Skip Email',
		name: 'skipEmail',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['documentActions'], operation: ['send'] } },
		description: 'If enabled, D4Sign will not send emails to signers',
	},
	{
		displayName: 'Workflow',
		name: 'workflow',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['documentActions'], operation: ['send'] } },
		description: 'If enabled, activate workflow sending',
	},
	{
		displayName: 'Comment',
		name: 'comment',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['documentActions'], operation: ['cancel'] } },
		description: 'Reason/comment for the cancellation',
	},
	{
		displayName: 'Download Type',
		name: 'downloadType',
		type: 'options',
		options: [
			{ name: 'Original', value: 'original' },
			{ name: 'ZIP', value: 'zip' },
			{ name: 'PDF', value: 'pdf' },
		],
		default: 'original',
		displayOptions: { show: { resource: ['documentActions'], operation: ['download'] } },
		description: 'File type to download',
	},
	{
		displayName: 'Language',
		name: 'downloadLanguage',
		type: 'options',
		options: [
			{ name: 'Portuguese (pt)', value: 'pt' },
			{ name: 'English (en)', value: 'en' },
		],
		default: 'pt',
		displayOptions: { show: { resource: ['documentActions'], operation: ['download'] } },
		description: 'Language for the generated documents',
	},
	{
		displayName: 'Include Signer Documents',
		name: 'includeSignerDocuments',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['documentActions'], operation: ['download'] } },
		description: 'If enabled, include signer documents in the download',
	},
	{
		displayName: 'Base64 Encoding',
		name: 'downloadEncoding',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['documentActions'], operation: ['download'] } },
		description: 'If enabled, request a Base64-encoded download (D4Sign returns a URL to a .txt content)',
	},
	{
		displayName: 'Binary Property',
		name: 'downloadBinaryPropertyName',
		type: 'string',
		default: 'data',
		displayOptions: { show: { resource: ['documentActions'], operation: ['download'] } },
		description: 'Name of the binary property where the downloaded file should be stored',
	},
	{
		displayName: 'Signer Email',
		name: 'highlightSignerEmail',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['documentActions'], operation: ['addHighlight'] } },
		description: 'Email of the signer',
	},
	{
		displayName: 'Key Signer',
		name: 'highlightKeySigner',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['documentActions'], operation: ['addHighlight'] } },
		description: 'Key signer value from D4Sign (key_signer)',
	},
	{
		displayName: 'Highlight Text',
		name: 'highlightText',
		type: 'string',
		typeOptions: { rows: 4 },
		required: true,
		default: '',
		displayOptions: { show: { resource: ['documentActions'], operation: ['addHighlight'] } },
		description: 'Text to be highlighted / clause text',
	},
	{
		displayName: 'Recipient (Email or Phone)',
		name: 'resendRecipient',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['documentActions'], operation: ['resend'] } },
		description: 'Email or phone number that should receive the signing link',
	},
	{
		displayName: 'Key Signer',
		name: 'resendKeySigner',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['documentActions'], operation: ['resend'] } },
		description: 'Key signer value from D4Sign (key-signer)',
	},
];
